### ISSUE TITLE
Get Usage per Day / Week / Quarter of Hours

### ISSUE THREAD

**Issue by benji1703** [GuyKh/iec-custom-component#68]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/iec/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

Based on the resolution (1/2/3) in the API we could get the usage - and this could be handled over to a nice graph to show usage + price per day (week or hours or month)

### Describe alternatives you've considered

From the https://iecapi.iec.co.il/api/Consumption/RemoteReadingRange/
  "fromDate": "2024-01-01",
  "resolution": 3 / 2 / 1

### Additional context

N/A

**Comment by GuyKh** [comment]
Since you already have LongTerm Statistics in the Energy Dashboard, you can achieve Hourly/Daily/Monthly/Weekly view.
![image](https://github.com/GuyKh/iec-custom-component/assets/3136012/1a5c9b93-4241-47de-8262-e9d1144de0b2)


For 15min resolution - since IEC publishes the last 15 min data atleast 4 hrs back, I don't see the the use for that honestly.
